imagePullSecrets:
  - name: ghcr-creds

backend:
  deployment:
    replicaCount: 1
    image:
      tag: "sha-70929ae"
    env:
      - name: SPRING_DATASOURCE_URL
        value: "jdbc:postgresql://time-tracking-postgresql.time-tracking-dev.svc.cluster.local:5432/timetracking"
      - name: SPRING_DATASOURCE_USERNAME
        value: "timetracking_user"
      - name: SPRING_DATASOURCE_PASSWORD
        value: "timetracking123"
      - name: SPRING_SECURITY_OAUTH2_RESOURCESERVER_JWT_ISSUER_URI
        value: "https://keycloak-dev.localtest.me/realms/dev"
      - name: SPRING_SECURITY_OAUTH2_RESOURCESERVER_JWT_JWK_SET_URI
        value: "http://time-tracking-keycloak.time-tracking-dev.svc.cluster.local/realms/dev/protocol/openid-connect/certs"

frontend:
  image:
    tag: "latest"
  env:
    - name: KEYCLOAK_URL
      value: "https://keycloak-dev.localtest.me/"
    - name: KEYCLOAK_REALM
      value: "dev"
    - name: KEYCLOAK_CLIENT_ID
      value: "time-tracking-app"
    - name: API_BASE_URL
      value: "https://time-tracking-dev.localtest.me/"

ingress:
  enabled: true
  className: "nginx"
  hosts:
    - host: time-tracking-dev.localtest.me
      paths:
        - path: /
          pathType: Prefix
          service:
            name: frontend
        - path: /api
          pathType: Prefix
          service:
            name: backend
  tls:
    - hosts:
        - time-tracking-dev.localtest.me
      secretName: time-tracking-local-tls

keycloak:
  ingress:
    tls: true
    extraTls:
      - hosts:
          - keycloak-dev.localtest.me
        secretName: keycloak-local-tls
  externalDatabase:
    host: time-tracking-postgresql.time-tracking-dev.svc.cluster.local
    port: 5432
