apiVersion: v2
name: time-tracking-app-backend
description: A Helm chart for deploying the Time Tracking Application backend
type: application
version: 0.1.0
appVersion: "1.0.0"
dependencies:
  - name: keycloak
    version: 25.2.0
    repository: "oci://registry-1.docker.io/bitnamicharts/keycloak"
  - name: postgresql
    version: 18.1.11
    repository: "oci://registry-1.docker.io/bitnamicharts/postgresql"