deployment:
  replicaCount: 1
  env:
    - name: SPRING_DATASOURCE_URL
      value: "jdbc:postgresql://time-tracking-postgresql.time-tracking-dev.svc.cluster.local:5432/timetracking"
    - name: SPRING_DATASOURCE_USERNAME
      value: "timetracking_user"
    - name: SPRING_DATASOURCE_PASSWORD
      value: "timetracking123"
    - name: SPRING_SECURITY_OAUTH2_RESOURCESERVER_JWT_ISSUER_URI
      value: "https://keycloak.localtest.me/realms/dev"

frontend:
  env:
    - name: KEYCLOAK_URL
      value: "https://keycloak.localtest.me/"
    - name: KEYCLOAK_REALM
      value: "dev"
    - name: KEYCLOAK_CLIENT_ID
      value: "time-tracking-app"
    - name: API_BASE_URL
      value: "https://time-tracking.localtest.me/"

ingress:
  enabled: true
  className: "nginx"
  hosts:
    - host: time-tracking.localtest.me
      paths:
        - path: /
          pathType: Prefix
          service:
            name: frontend
        - path: /api
          pathType: Prefix
          service:
            name: backend
  tls:
    - hosts:
        - time-tracking.localtest.me
      secretName: time-tracking-local-tls

keycloak:
  ingress:
    tls: true
    extraTls:
      - hosts:
          - keycloak.localtest.me
        secretName: keycloak-local-tls
  externalDatabase:
    host: time-tracking-postgresql.time-tracking-dev.svc.cluster.local
    port: 5432
