apiVersion: v1
kind: Service
metadata:
  name: {{ include "time-tracking-app.fullname" . }}
  labels:
    {{- include "time-tracking-app.labels" . | nindent 4 }}
    app.kubernetes.io/component: backend
spec:
  type: {{ .Values.backend.service.type }}
  ports:
    - name: http
      port: {{ .Values.backend.service.port }}
      targetPort: 8080
      protocol: TCP
  selector:
    {{- include "time-tracking-app.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: backend
