{{- if .Values.frontend.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "time-tracking-app.fullname" . }}-frontend
  labels:
    {{- include "time-tracking-app.labels" . | nindent 4 }}
    app.kubernetes.io/component: frontend
spec:
  type: {{ .Values.frontend.service.type }}
  ports:
    - name: http
      port: {{ .Values.frontend.service.port }}
      targetPort: {{ .Values.frontend.containerPort }}
      protocol: TCP
  selector:
    {{- include "time-tracking-app.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: frontend
{{- end }}
